apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: cli
  name: cli
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cli
    spec:
      containers:
      - image: ottar63/rpi_mysql_python_test
        name: client
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
